<?php

namespace AppBundle\Repository;

/**
 * PollItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollItemRepository extends \Doctrine\ORM\EntityRepository
{
}
