app_poll:
    resource: '@AppBundle/Resources/config/routing/poll.yml'
app_poll_item:
    resource: '@AppBundle/Resources/config/routing/pollItem.yml'
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



